/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	User:{
		posts:{
			where:{
				type:"PostWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"PostOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		postsCount:{
			where:{
				type:"PostWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		products:{
			where:{
				type:"ProductWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"ProductOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		productsCount:{
			where:{
				type:"ProductWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	UserOauthProviderType: "enum",
	UserWhereUniqueInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UserWhereInput:{
		AND:{
			type:"UserWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"UserWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"UserWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		oauthProvider:{
			type:"UserOauthProviderTypeNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		oauthProfileId:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		posts:{
			type:"PostManyRelationFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		products:{
			type:"ProductManyRelationFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	IDFilter:{
		equals:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		notIn:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"IDFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	StringFilter:{
		equals:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		notIn:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		startsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		endsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		mode:{
			type:"QueryMode",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedStringFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	QueryMode: "enum",
	NestedStringFilter:{
		equals:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		notIn:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		startsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		endsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedStringFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UserOauthProviderTypeNullableFilter:{
		equals:{
			type:"UserOauthProviderType",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"UserOauthProviderType",
			array:true,
			arrayRequired:false,
			required:true
		},
		notIn:{
			type:"UserOauthProviderType",
			array:true,
			arrayRequired:false,
			required:true
		},
		not:{
			type:"UserOauthProviderTypeNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	PostManyRelationFilter:{
		every:{
			type:"PostWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		some:{
			type:"PostWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		none:{
			type:"PostWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProductManyRelationFilter:{
		every:{
			type:"ProductWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		some:{
			type:"ProductWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		none:{
			type:"ProductWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UserOrderByInput:{
		id:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		oauthProvider:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		oauthProfileId:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OrderDirection: "enum",
	UserUpdateInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		oauthProvider:{
			type:"UserOauthProviderType",
			array:false,
			arrayRequired:false,
			required:false
		},
		oauthProfileId:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		posts:{
			type:"PostRelateToManyForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		products:{
			type:"ProductRelateToManyForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	PostRelateToManyForUpdateInput:{
		disconnect:{
			type:"PostWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		set:{
			type:"PostWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		create:{
			type:"PostCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"PostWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	ProductRelateToManyForUpdateInput:{
		disconnect:{
			type:"ProductWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		set:{
			type:"ProductWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		create:{
			type:"ProductCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"ProductWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	UserUpdateArgs:{
		where:{
			type:"UserWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:true
		},
		data:{
			type:"UserUpdateInput",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	UserCreateInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		oauthProvider:{
			type:"UserOauthProviderType",
			array:false,
			arrayRequired:false,
			required:false
		},
		oauthProfileId:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		posts:{
			type:"PostRelateToManyForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		products:{
			type:"ProductRelateToManyForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	PostRelateToManyForCreateInput:{
		create:{
			type:"PostCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"PostWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	ProductRelateToManyForCreateInput:{
		create:{
			type:"ProductCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"ProductWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	Post:{
		tags:{
			where:{
				type:"TagWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"TagOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		tagsCount:{
			where:{
				type:"TagWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	Post_content_Document:{
		document:{
			hydrateRelationships:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	DateTime: "String",
	PostWhereUniqueInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	PostWhereInput:{
		AND:{
			type:"PostWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"PostWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"PostWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"StringNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		publishDate:{
			type:"DateTimeNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		author:{
			type:"UserWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		tags:{
			type:"TagManyRelationFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	StringNullableFilter:{
		equals:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		notIn:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		startsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		endsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		mode:{
			type:"QueryMode",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedStringNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	NestedStringNullableFilter:{
		equals:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		notIn:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		startsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		endsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedStringNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	DateTimeNullableFilter:{
		equals:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		notIn:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"DateTimeNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	TagManyRelationFilter:{
		every:{
			type:"TagWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		some:{
			type:"TagWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		none:{
			type:"TagWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	PostOrderByInput:{
		id:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		publishDate:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	PostUpdateInput:{
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		content:{
			type:"JSON",
			array:false,
			arrayRequired:false,
			required:false
		},
		publishDate:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		author:{
			type:"UserRelateToOneForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		tags:{
			type:"TagRelateToManyForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UserRelateToOneForUpdateInput:{
		create:{
			type:"UserCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		connect:{
			type:"UserWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		disconnect:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	TagRelateToManyForUpdateInput:{
		disconnect:{
			type:"TagWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		set:{
			type:"TagWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		create:{
			type:"TagCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"TagWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	PostUpdateArgs:{
		where:{
			type:"PostWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:true
		},
		data:{
			type:"PostUpdateInput",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	PostCreateInput:{
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		content:{
			type:"JSON",
			array:false,
			arrayRequired:false,
			required:false
		},
		publishDate:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		author:{
			type:"UserRelateToOneForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		tags:{
			type:"TagRelateToManyForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UserRelateToOneForCreateInput:{
		create:{
			type:"UserCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		connect:{
			type:"UserWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	TagRelateToManyForCreateInput:{
		create:{
			type:"TagCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"TagWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	Product:{
		photo:{
			where:{
				type:"ProductImageWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"ProductImageOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		photoCount:{
			where:{
				type:"ProductImageWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		skus:{
			where:{
				type:"SKUWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"SKUOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		skusCount:{
			where:{
				type:"SKUWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		skuValues:{
			where:{
				type:"SKUValueWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"SKUValueOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		skuValuesCount:{
			where:{
				type:"SKUValueWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		options:{
			where:{
				type:"OptionWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"OptionOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		optionsCount:{
			where:{
				type:"OptionWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		optionValues:{
			where:{
				type:"OptionValueWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"OptionValueOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		optionValuesCount:{
			where:{
				type:"OptionValueWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	ProductWhereUniqueInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProductWhereInput:{
		AND:{
			type:"ProductWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"ProductWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"ProductWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		photo:{
			type:"ProductImageManyRelationFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"StringNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"UserWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		skus:{
			type:"SKUManyRelationFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		skuValues:{
			type:"SKUValueManyRelationFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		options:{
			type:"OptionManyRelationFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		optionValues:{
			type:"OptionValueManyRelationFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		category:{
			type:"CategoryWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProductImageManyRelationFilter:{
		every:{
			type:"ProductImageWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		some:{
			type:"ProductImageWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		none:{
			type:"ProductImageWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKUManyRelationFilter:{
		every:{
			type:"SKUWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		some:{
			type:"SKUWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		none:{
			type:"SKUWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKUValueManyRelationFilter:{
		every:{
			type:"SKUValueWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		some:{
			type:"SKUValueWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		none:{
			type:"SKUValueWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionManyRelationFilter:{
		every:{
			type:"OptionWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		some:{
			type:"OptionWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		none:{
			type:"OptionWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionValueManyRelationFilter:{
		every:{
			type:"OptionValueWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		some:{
			type:"OptionValueWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		none:{
			type:"OptionValueWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProductOrderByInput:{
		id:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProductUpdateInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		photo:{
			type:"ProductImageRelateToManyForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"UserRelateToOneForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		skus:{
			type:"SKURelateToManyForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		skuValues:{
			type:"SKUValueRelateToManyForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		options:{
			type:"OptionRelateToManyForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		optionValues:{
			type:"OptionValueRelateToManyForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		category:{
			type:"CategoryRelateToOneForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProductImageRelateToManyForUpdateInput:{
		disconnect:{
			type:"ProductImageWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		set:{
			type:"ProductImageWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		create:{
			type:"ProductImageCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"ProductImageWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	SKURelateToManyForUpdateInput:{
		disconnect:{
			type:"SKUWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		set:{
			type:"SKUWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		create:{
			type:"SKUCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"SKUWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	SKUValueRelateToManyForUpdateInput:{
		disconnect:{
			type:"SKUValueWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		set:{
			type:"SKUValueWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		create:{
			type:"SKUValueCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"SKUValueWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	OptionRelateToManyForUpdateInput:{
		disconnect:{
			type:"OptionWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		set:{
			type:"OptionWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		create:{
			type:"OptionCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"OptionWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	OptionValueRelateToManyForUpdateInput:{
		disconnect:{
			type:"OptionValueWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		set:{
			type:"OptionValueWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		create:{
			type:"OptionValueCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"OptionValueWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	CategoryRelateToOneForUpdateInput:{
		create:{
			type:"CategoryCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		connect:{
			type:"CategoryWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		disconnect:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProductUpdateArgs:{
		where:{
			type:"ProductWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:true
		},
		data:{
			type:"ProductUpdateInput",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	ProductCreateInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		photo:{
			type:"ProductImageRelateToManyForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"UserRelateToOneForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		skus:{
			type:"SKURelateToManyForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		skuValues:{
			type:"SKUValueRelateToManyForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		options:{
			type:"OptionRelateToManyForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		optionValues:{
			type:"OptionValueRelateToManyForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		category:{
			type:"CategoryRelateToOneForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProductImageRelateToManyForCreateInput:{
		create:{
			type:"ProductImageCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"ProductImageWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	SKURelateToManyForCreateInput:{
		create:{
			type:"SKUCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"SKUWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	SKUValueRelateToManyForCreateInput:{
		create:{
			type:"SKUValueCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"SKUValueWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	OptionRelateToManyForCreateInput:{
		create:{
			type:"OptionCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"OptionWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	OptionValueRelateToManyForCreateInput:{
		create:{
			type:"OptionValueCreateInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		connect:{
			type:"OptionValueWhereUniqueInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	CategoryRelateToOneForCreateInput:{
		create:{
			type:"CategoryCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		connect:{
			type:"CategoryWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CloudinaryImage_File:{
		publicUrlTransformed:{
			transformation:{
				type:"CloudinaryImageFormat",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	CloudinaryImageFormat:{
		prettyName:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		width:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		height:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		crop:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		aspect_ratio:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gravity:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		zoom:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		x:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		y:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		format:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		fetch_format:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		quality:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		radius:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		angle:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		effect:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		opacity:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		border:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		background:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		overlay:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		underlay:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		default_image:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		delay:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		color:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		color_space:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		dpr:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		page:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		density:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		flags:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		transformation:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProductImageWhereUniqueInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProductImageWhereInput:{
		AND:{
			type:"ProductImageWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"ProductImageWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"ProductImageWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		altText:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		product:{
			type:"ProductWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		option:{
			type:"OptionWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		optionValue:{
			type:"OptionValueWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProductImageOrderByInput:{
		id:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		altText:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProductImageUpdateInput:{
		image:{
			type:"Upload",
			array:false,
			arrayRequired:false,
			required:false
		},
		altText:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		product:{
			type:"ProductRelateToOneForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		option:{
			type:"OptionRelateToOneForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		optionValue:{
			type:"OptionValueRelateToOneForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	Upload: "String",
	ProductRelateToOneForUpdateInput:{
		create:{
			type:"ProductCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		connect:{
			type:"ProductWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		disconnect:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionRelateToOneForUpdateInput:{
		create:{
			type:"OptionCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		connect:{
			type:"OptionWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		disconnect:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionValueRelateToOneForUpdateInput:{
		create:{
			type:"OptionValueCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		connect:{
			type:"OptionValueWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		disconnect:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProductImageUpdateArgs:{
		where:{
			type:"ProductImageWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:true
		},
		data:{
			type:"ProductImageUpdateInput",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	ProductImageCreateInput:{
		image:{
			type:"Upload",
			array:false,
			arrayRequired:false,
			required:false
		},
		altText:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		product:{
			type:"ProductRelateToOneForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		option:{
			type:"OptionRelateToOneForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		optionValue:{
			type:"OptionValueRelateToOneForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	ProductRelateToOneForCreateInput:{
		create:{
			type:"ProductCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		connect:{
			type:"ProductWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionRelateToOneForCreateInput:{
		create:{
			type:"OptionCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		connect:{
			type:"OptionWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionValueRelateToOneForCreateInput:{
		create:{
			type:"OptionValueCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		connect:{
			type:"OptionValueWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	Tag:{
		posts:{
			where:{
				type:"PostWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"PostOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		postsCount:{
			where:{
				type:"PostWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	TagWhereUniqueInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	TagWhereInput:{
		AND:{
			type:"TagWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"TagWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"TagWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		posts:{
			type:"PostManyRelationFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	TagOrderByInput:{
		id:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	TagUpdateInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		posts:{
			type:"PostRelateToManyForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	TagUpdateArgs:{
		where:{
			type:"TagWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:true
		},
		data:{
			type:"TagUpdateInput",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	TagCreateInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		posts:{
			type:"PostRelateToManyForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CategoryWhereUniqueInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CategoryWhereInput:{
		AND:{
			type:"CategoryWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"CategoryWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"CategoryWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CategoryOrderByInput:{
		id:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CategoryUpdateInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	CategoryUpdateArgs:{
		where:{
			type:"CategoryWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:true
		},
		data:{
			type:"CategoryUpdateInput",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	CategoryCreateInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKUWhereUniqueInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		sku:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKUWhereInput:{
		AND:{
			type:"SKUWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"SKUWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"SKUWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		sku:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		product:{
			type:"ProductWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		stock:{
			type:"IntNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	IntNullableFilter:{
		equals:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"Int",
			array:true,
			arrayRequired:false,
			required:true
		},
		notIn:{
			type:"Int",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"IntNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKUOrderByInput:{
		id:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		sku:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		stock:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKUUpdateInput:{
		sku:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		product:{
			type:"ProductRelateToOneForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		stock:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKUUpdateArgs:{
		where:{
			type:"SKUWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:true
		},
		data:{
			type:"SKUUpdateInput",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	SKUCreateInput:{
		sku:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		product:{
			type:"ProductRelateToOneForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		stock:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKUValue:{
		options:{
			where:{
				type:"OptionWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"OptionOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		optionsCount:{
			where:{
				type:"OptionWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		optionValues:{
			where:{
				type:"OptionValueWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"OptionValueOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		optionValuesCount:{
			where:{
				type:"OptionValueWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	SKUValueWhereUniqueInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKUValueWhereInput:{
		AND:{
			type:"SKUValueWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"SKUValueWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"SKUValueWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		product:{
			type:"ProductWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		SKU:{
			type:"SKUWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		options:{
			type:"OptionManyRelationFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		optionValues:{
			type:"OptionValueManyRelationFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKUValueOrderByInput:{
		id:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKUValueUpdateInput:{
		product:{
			type:"ProductRelateToOneForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		SKU:{
			type:"SKURelateToOneForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		options:{
			type:"OptionRelateToManyForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		optionValues:{
			type:"OptionValueRelateToManyForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKURelateToOneForUpdateInput:{
		create:{
			type:"SKUCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		connect:{
			type:"SKUWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		disconnect:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKUValueUpdateArgs:{
		where:{
			type:"SKUValueWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:true
		},
		data:{
			type:"SKUValueUpdateInput",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	SKUValueCreateInput:{
		product:{
			type:"ProductRelateToOneForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		SKU:{
			type:"SKURelateToOneForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		options:{
			type:"OptionRelateToManyForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		optionValues:{
			type:"OptionValueRelateToManyForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKURelateToOneForCreateInput:{
		create:{
			type:"SKUCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		connect:{
			type:"SKUWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionWhereUniqueInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionWhereInput:{
		AND:{
			type:"OptionWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"OptionWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"OptionWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		product:{
			type:"ProductWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionOrderByInput:{
		id:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionUpdateInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		product:{
			type:"ProductRelateToOneForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionUpdateArgs:{
		where:{
			type:"OptionWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:true
		},
		data:{
			type:"OptionUpdateInput",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	OptionCreateInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		product:{
			type:"ProductRelateToOneForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionValueWhereUniqueInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionValueWhereInput:{
		AND:{
			type:"OptionValueWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"OptionValueWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"OptionValueWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"IDFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		product:{
			type:"ProductWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		option:{
			type:"OptionWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionValueOrderByInput:{
		id:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"OrderDirection",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionValueUpdateInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		product:{
			type:"ProductRelateToOneForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		option:{
			type:"OptionRelateToOneForUpdateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OptionValueUpdateArgs:{
		where:{
			type:"OptionValueWhereUniqueInput",
			array:false,
			arrayRequired:false,
			required:true
		},
		data:{
			type:"OptionValueUpdateInput",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	OptionValueCreateInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		product:{
			type:"ProductRelateToOneForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		option:{
			type:"OptionRelateToOneForCreateInput",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	JSON: "String",
	Mutation:{
		createUser:{
			data:{
				type:"UserCreateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createUsers:{
			data:{
				type:"UserCreateInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		updateUser:{
			where:{
				type:"UserWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"UserUpdateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateUsers:{
			data:{
				type:"UserUpdateArgs",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		deleteUser:{
			where:{
				type:"UserWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteUsers:{
			where:{
				type:"UserWhereUniqueInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		createPost:{
			data:{
				type:"PostCreateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createPosts:{
			data:{
				type:"PostCreateInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		updatePost:{
			where:{
				type:"PostWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"PostUpdateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updatePosts:{
			data:{
				type:"PostUpdateArgs",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		deletePost:{
			where:{
				type:"PostWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deletePosts:{
			where:{
				type:"PostWhereUniqueInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		createProduct:{
			data:{
				type:"ProductCreateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createProducts:{
			data:{
				type:"ProductCreateInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		updateProduct:{
			where:{
				type:"ProductWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"ProductUpdateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateProducts:{
			data:{
				type:"ProductUpdateArgs",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		deleteProduct:{
			where:{
				type:"ProductWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteProducts:{
			where:{
				type:"ProductWhereUniqueInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		createProductImage:{
			data:{
				type:"ProductImageCreateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createProductImages:{
			data:{
				type:"ProductImageCreateInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		updateProductImage:{
			where:{
				type:"ProductImageWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"ProductImageUpdateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateProductImages:{
			data:{
				type:"ProductImageUpdateArgs",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		deleteProductImage:{
			where:{
				type:"ProductImageWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteProductImages:{
			where:{
				type:"ProductImageWhereUniqueInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		createTag:{
			data:{
				type:"TagCreateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createTags:{
			data:{
				type:"TagCreateInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		updateTag:{
			where:{
				type:"TagWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"TagUpdateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateTags:{
			data:{
				type:"TagUpdateArgs",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		deleteTag:{
			where:{
				type:"TagWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteTags:{
			where:{
				type:"TagWhereUniqueInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		createCategory:{
			data:{
				type:"CategoryCreateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createCategories:{
			data:{
				type:"CategoryCreateInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		updateCategory:{
			where:{
				type:"CategoryWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"CategoryUpdateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateCategories:{
			data:{
				type:"CategoryUpdateArgs",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		deleteCategory:{
			where:{
				type:"CategoryWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteCategories:{
			where:{
				type:"CategoryWhereUniqueInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		createSKU:{
			data:{
				type:"SKUCreateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createSKUS:{
			data:{
				type:"SKUCreateInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		updateSKU:{
			where:{
				type:"SKUWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"SKUUpdateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateSKUS:{
			data:{
				type:"SKUUpdateArgs",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		deleteSKU:{
			where:{
				type:"SKUWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteSKUS:{
			where:{
				type:"SKUWhereUniqueInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		createSKUValue:{
			data:{
				type:"SKUValueCreateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createSKUValues:{
			data:{
				type:"SKUValueCreateInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		updateSKUValue:{
			where:{
				type:"SKUValueWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"SKUValueUpdateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateSKUValues:{
			data:{
				type:"SKUValueUpdateArgs",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		deleteSKUValue:{
			where:{
				type:"SKUValueWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteSKUValues:{
			where:{
				type:"SKUValueWhereUniqueInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		createOption:{
			data:{
				type:"OptionCreateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createOptions:{
			data:{
				type:"OptionCreateInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		updateOption:{
			where:{
				type:"OptionWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"OptionUpdateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateOptions:{
			data:{
				type:"OptionUpdateArgs",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		deleteOption:{
			where:{
				type:"OptionWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteOptions:{
			where:{
				type:"OptionWhereUniqueInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		createOptionValue:{
			data:{
				type:"OptionValueCreateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createOptionValues:{
			data:{
				type:"OptionValueCreateInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		updateOptionValue:{
			where:{
				type:"OptionValueWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"OptionValueUpdateInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateOptionValues:{
			data:{
				type:"OptionValueUpdateArgs",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		deleteOptionValue:{
			where:{
				type:"OptionValueWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		deleteOptionValues:{
			where:{
				type:"OptionValueWhereUniqueInput",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		authenticateUserWithPassword:{
			email:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			},
			password:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		createInitialUser:{
			data:{
				type:"CreateInitialUserInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	CreateInitialUserInput:{
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	Query:{
		users:{
			where:{
				type:"UserWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"UserOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		user:{
			where:{
				type:"UserWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		usersCount:{
			where:{
				type:"UserWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		posts:{
			where:{
				type:"PostWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"PostOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		post:{
			where:{
				type:"PostWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		postsCount:{
			where:{
				type:"PostWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		products:{
			where:{
				type:"ProductWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"ProductOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		product:{
			where:{
				type:"ProductWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		productsCount:{
			where:{
				type:"ProductWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		productImages:{
			where:{
				type:"ProductImageWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"ProductImageOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		productImage:{
			where:{
				type:"ProductImageWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		productImagesCount:{
			where:{
				type:"ProductImageWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		tags:{
			where:{
				type:"TagWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"TagOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		tag:{
			where:{
				type:"TagWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		tagsCount:{
			where:{
				type:"TagWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		categories:{
			where:{
				type:"CategoryWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"CategoryOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		category:{
			where:{
				type:"CategoryWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		categoriesCount:{
			where:{
				type:"CategoryWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		sKUS:{
			where:{
				type:"SKUWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"SKUOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		sKU:{
			where:{
				type:"SKUWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		sKUSCount:{
			where:{
				type:"SKUWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		sKUValues:{
			where:{
				type:"SKUValueWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"SKUValueOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		sKUValue:{
			where:{
				type:"SKUValueWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		sKUValuesCount:{
			where:{
				type:"SKUValueWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		options:{
			where:{
				type:"OptionWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"OptionOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		option:{
			where:{
				type:"OptionWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		optionsCount:{
			where:{
				type:"OptionWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		optionValues:{
			where:{
				type:"OptionValueWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"OptionValueOrderByInput",
				array:true,
				arrayRequired:true,
				required:true
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		optionValue:{
			where:{
				type:"OptionValueWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		optionValuesCount:{
			where:{
				type:"OptionValueWhereInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	KeystoneAdminMeta:{
		list:{
			key:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	KeystoneAdminUIFieldMeta:{
		itemView:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	KeystoneAdminUIFieldMetaCreateViewFieldMode: "enum",
	KeystoneAdminUIFieldMetaListViewFieldMode: "enum",
	KeystoneAdminUIFieldMetaItemViewFieldMode: "enum",
	KeystoneAdminUISortDirection: "enum"
}

export const ReturnTypes: Record<string,any> = {
	User:{
		id:"ID",
		name:"String",
		email:"String",
		oauthProvider:"UserOauthProviderType",
		oauthProfileId:"String",
		password:"PasswordState",
		posts:"Post",
		postsCount:"Int",
		products:"Product",
		productsCount:"Int"
	},
	PasswordState:{
		isSet:"Boolean"
	},
	Post:{
		id:"ID",
		title:"String",
		status:"String",
		content:"Post_content_Document",
		publishDate:"DateTime",
		author:"User",
		tags:"Tag",
		tagsCount:"Int"
	},
	Post_content_Document:{
		document:"JSON"
	},
	Product:{
		id:"ID",
		name:"String",
		description:"String",
		photo:"ProductImage",
		photoCount:"Int",
		status:"String",
		user:"User",
		skus:"SKU",
		skusCount:"Int",
		skuValues:"SKUValue",
		skuValuesCount:"Int",
		options:"Option",
		optionsCount:"Int",
		optionValues:"OptionValue",
		optionValuesCount:"Int",
		category:"Category"
	},
	ProductImage:{
		id:"ID",
		image:"CloudinaryImage_File",
		altText:"String",
		product:"Product",
		option:"Option",
		optionValue:"OptionValue"
	},
	CloudinaryImage_File:{
		id:"ID",
		filename:"String",
		originalFilename:"String",
		mimetype:"String",
		encoding:"String",
		publicUrl:"String",
		publicUrlTransformed:"String"
	},
	Tag:{
		id:"ID",
		name:"String",
		posts:"Post",
		postsCount:"Int"
	},
	Category:{
		id:"ID",
		name:"String"
	},
	SKU:{
		id:"ID",
		sku:"String",
		product:"Product",
		stock:"Int"
	},
	SKUValue:{
		id:"ID",
		product:"Product",
		SKU:"SKU",
		options:"Option",
		optionsCount:"Int",
		optionValues:"OptionValue",
		optionValuesCount:"Int"
	},
	Option:{
		id:"ID",
		name:"String",
		product:"Product"
	},
	OptionValue:{
		id:"ID",
		name:"String",
		product:"Product",
		option:"Option"
	},
	Mutation:{
		createUser:"User",
		createUsers:"User",
		updateUser:"User",
		updateUsers:"User",
		deleteUser:"User",
		deleteUsers:"User",
		createPost:"Post",
		createPosts:"Post",
		updatePost:"Post",
		updatePosts:"Post",
		deletePost:"Post",
		deletePosts:"Post",
		createProduct:"Product",
		createProducts:"Product",
		updateProduct:"Product",
		updateProducts:"Product",
		deleteProduct:"Product",
		deleteProducts:"Product",
		createProductImage:"ProductImage",
		createProductImages:"ProductImage",
		updateProductImage:"ProductImage",
		updateProductImages:"ProductImage",
		deleteProductImage:"ProductImage",
		deleteProductImages:"ProductImage",
		createTag:"Tag",
		createTags:"Tag",
		updateTag:"Tag",
		updateTags:"Tag",
		deleteTag:"Tag",
		deleteTags:"Tag",
		createCategory:"Category",
		createCategories:"Category",
		updateCategory:"Category",
		updateCategories:"Category",
		deleteCategory:"Category",
		deleteCategories:"Category",
		createSKU:"SKU",
		createSKUS:"SKU",
		updateSKU:"SKU",
		updateSKUS:"SKU",
		deleteSKU:"SKU",
		deleteSKUS:"SKU",
		createSKUValue:"SKUValue",
		createSKUValues:"SKUValue",
		updateSKUValue:"SKUValue",
		updateSKUValues:"SKUValue",
		deleteSKUValue:"SKUValue",
		deleteSKUValues:"SKUValue",
		createOption:"Option",
		createOptions:"Option",
		updateOption:"Option",
		updateOptions:"Option",
		deleteOption:"Option",
		deleteOptions:"Option",
		createOptionValue:"OptionValue",
		createOptionValues:"OptionValue",
		updateOptionValue:"OptionValue",
		updateOptionValues:"OptionValue",
		deleteOptionValue:"OptionValue",
		deleteOptionValues:"OptionValue",
		endSession:"Boolean",
		authenticateUserWithPassword:"UserAuthenticationWithPasswordResult",
		createInitialUser:"UserAuthenticationWithPasswordSuccess"
	},
	UserAuthenticationWithPasswordResult:{
		"...on UserAuthenticationWithPasswordSuccess":"UserAuthenticationWithPasswordSuccess",
		"...on UserAuthenticationWithPasswordFailure":"UserAuthenticationWithPasswordFailure"
	},
	UserAuthenticationWithPasswordSuccess:{
		sessionToken:"String",
		item:"User"
	},
	UserAuthenticationWithPasswordFailure:{
		message:"String"
	},
	Query:{
		users:"User",
		user:"User",
		usersCount:"Int",
		posts:"Post",
		post:"Post",
		postsCount:"Int",
		products:"Product",
		product:"Product",
		productsCount:"Int",
		productImages:"ProductImage",
		productImage:"ProductImage",
		productImagesCount:"Int",
		tags:"Tag",
		tag:"Tag",
		tagsCount:"Int",
		categories:"Category",
		category:"Category",
		categoriesCount:"Int",
		sKUS:"SKU",
		sKU:"SKU",
		sKUSCount:"Int",
		sKUValues:"SKUValue",
		sKUValue:"SKUValue",
		sKUValuesCount:"Int",
		options:"Option",
		option:"Option",
		optionsCount:"Int",
		optionValues:"OptionValue",
		optionValue:"OptionValue",
		optionValuesCount:"Int",
		keystone:"KeystoneMeta",
		authenticatedItem:"AuthenticatedItem"
	},
	AuthenticatedItem:{
		"...on User":"User"
	},
	KeystoneMeta:{
		adminMeta:"KeystoneAdminMeta"
	},
	KeystoneAdminMeta:{
		enableSignout:"Boolean",
		enableSessionItem:"Boolean",
		lists:"KeystoneAdminUIListMeta",
		list:"KeystoneAdminUIListMeta"
	},
	KeystoneAdminUIListMeta:{
		key:"String",
		itemQueryName:"String",
		listQueryName:"String",
		hideCreate:"Boolean",
		hideDelete:"Boolean",
		path:"String",
		label:"String",
		singular:"String",
		plural:"String",
		description:"String",
		initialColumns:"String",
		pageSize:"Int",
		labelField:"String",
		fields:"KeystoneAdminUIFieldMeta",
		initialSort:"KeystoneAdminUISort",
		isHidden:"Boolean"
	},
	KeystoneAdminUIFieldMeta:{
		path:"String",
		label:"String",
		isOrderable:"Boolean",
		isFilterable:"Boolean",
		fieldMeta:"JSON",
		viewsIndex:"Int",
		customViewsIndex:"Int",
		createView:"KeystoneAdminUIFieldMetaCreateView",
		listView:"KeystoneAdminUIFieldMetaListView",
		itemView:"KeystoneAdminUIFieldMetaItemView",
		search:"QueryMode"
	},
	KeystoneAdminUIFieldMetaCreateView:{
		fieldMode:"KeystoneAdminUIFieldMetaCreateViewFieldMode"
	},
	KeystoneAdminUIFieldMetaListView:{
		fieldMode:"KeystoneAdminUIFieldMetaListViewFieldMode"
	},
	KeystoneAdminUIFieldMetaItemView:{
		fieldMode:"KeystoneAdminUIFieldMetaItemViewFieldMode"
	},
	KeystoneAdminUISort:{
		field:"String",
		direction:"KeystoneAdminUISortDirection"
	}
}